import type { DynamicVideoProps } from "@video/schema/scene-schema";

// GENERADO por scripts/build-module-examples.ts — no editar a mano.
// Fuente: audio_m1/ + m1_fotografia/ + narraciones_m1_subtitulos.txt
// Una escena por línea de narración: su audio manda la duración y su
// fotografía es la imagen. La media vive en render-server/uploads/, así que el
// servidor de render tiene que estar arriba para verla.
const MEDIA = "http://localhost:4000/uploads/modulos/m1";

export const moduloConceptos: DynamicVideoProps = {
  settings: { subtitles: true },
  scenes: [
    {
      id: "m1-1",
      name: "La topografía es la ciencia que mide y…",
      type: "image",
      durationInSeconds: 5.9,
      imageUrl: `${MEDIA}/fotografia_1.png`,
      audioUrl: `${MEDIA}/escena_1.mp3`,
      accentColor: "#1a6bff",
      script: "La topografía es la ciencia que mide y representa la superficie del terreno.",
    },
    {
      id: "m1-2",
      name: "Ubica cada punto dentro de un sistema de…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_2.png`,
      audioUrl: `${MEDIA}/escena_2.mp3`,
      accentColor: "#1a6bff",
      script: "Ubica cada punto dentro de un sistema de referencia comun.",
    },
    {
      id: "m1-3",
      name: "Toda obra civil empieza con un…",
      type: "image",
      durationInSeconds: 3.9,
      imageUrl: `${MEDIA}/fotografia_3.png`,
      audioUrl: `${MEDIA}/escena_3.mp3`,
      accentColor: "#1a6bff",
      script: "Toda obra civil empieza con un levantamiento topográfico.",
    },
    {
      id: "m1-4",
      name: "Sin datos precisos del terreno no se puede…",
      type: "image",
      durationInSeconds: 4.2,
      imageUrl: `${MEDIA}/fotografia_4.png`,
      audioUrl: `${MEDIA}/escena_4.mp3`,
      accentColor: "#1a6bff",
      script: "Sin datos precisos del terreno no se puede diseñar ni construir.",
    },
    {
      id: "m1-5",
      name: "Tampoco se puede replantear ni controlar la…",
      type: "image",
      durationInSeconds: 4.8,
      imageUrl: `${MEDIA}/fotografia_5.png`,
      audioUrl: `${MEDIA}/escena_5.mp3`,
      accentColor: "#1a6bff",
      script: "Tampoco se puede replantear ni controlar la ejecucion de la obra.",
    },
    {
      id: "m1-6",
      name: "El técnico de campo ejecuta las mediciones…",
      type: "image",
      durationInSeconds: 5,
      imageUrl: `${MEDIA}/fotografia_6.png`,
      audioUrl: `${MEDIA}/escena_6.mp3`,
      accentColor: "#1a6bff",
      script: "El técnico de campo ejecuta las mediciones y opera los instrumentos.",
    },
    {
      id: "m1-7",
      name: "Tambien registra los datos que alimentan…",
      type: "image",
      durationInSeconds: 3.8,
      imageUrl: `${MEDIA}/fotografia_7.png`,
      audioUrl: `${MEDIA}/escena_7.mp3`,
      accentColor: "#1a6bff",
      script: "Tambien registra los datos que alimentan todo el proyecto.",
    },
    {
      id: "m1-8",
      name: "La precisión de su trabajo condiciona la…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_8.png`,
      audioUrl: `${MEDIA}/escena_8.mp3`,
      accentColor: "#1a6bff",
      script: "La precisión de su trabajo condiciona la calidad de la obra completa.",
    },
    {
      id: "m1-9",
      name: "Empecemos por los conceptos que debes…",
      type: "image",
      durationInSeconds: 4.5,
      imageUrl: `${MEDIA}/fotografia_9.png`,
      audioUrl: `${MEDIA}/escena_9.mp3`,
      accentColor: "#1a6bff",
      script: "Empecemos por los conceptos que debes dominar antes de salir a campo.",
    },
    {
      id: "m1-10",
      name: "El punto es la unidad mínima de medición en…",
      type: "image",
      durationInSeconds: 4.7,
      imageUrl: `${MEDIA}/fotografia_10.png`,
      audioUrl: `${MEDIA}/escena_10.mp3`,
      accentColor: "#1a6bff",
      script: "El punto es la unidad mínima de medición en topografía.",
    },
    {
      id: "m1-11",
      name: "Las líneas y los planos se construyen a…",
      type: "image",
      durationInSeconds: 5.1,
      imageUrl: `${MEDIA}/fotografia_11.png`,
      audioUrl: `${MEDIA}/escena_11.mp3`,
      accentColor: "#1a6bff",
      script: "Las líneas y los planos se construyen a partir de puntos referenciados.",
    },
    {
      id: "m1-12",
      name: "La planimetría estudia la posición de los…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_12.png`,
      audioUrl: `${MEDIA}/escena_12.mp3`,
      accentColor: "#1a6bff",
      script: "La planimetría estudia la posición de los puntos en el plano horizontal.",
    },
    {
      id: "m1-13",
      name: "La altimetría estudia las diferencias de…",
      type: "image",
      durationInSeconds: 5.2,
      imageUrl: `${MEDIA}/fotografia_13.png`,
      audioUrl: `${MEDIA}/escena_13.mp3`,
      accentColor: "#1a6bff",
      script: "La altimetría estudia las diferencias de altura entre esos mismos puntos.",
    },
    {
      id: "m1-14",
      name: "La cota es la altura de un punto respecto a…",
      type: "image",
      durationInSeconds: 5.6,
      imageUrl: `${MEDIA}/fotografia_14.png`,
      audioUrl: `${MEDIA}/escena_14.mp3`,
      accentColor: "#1a6bff",
      script: "La cota es la altura de un punto respecto a un plano de referencia.",
    },
    {
      id: "m1-15",
      name: "Ese plano suele ser el nivel medio del mar…",
      type: "image",
      durationInSeconds: 5.5,
      imageUrl: `${MEDIA}/fotografia_15.png`,
      audioUrl: `${MEDIA}/escena_15.mp3`,
      accentColor: "#1a6bff",
      script: "Ese plano suele ser el nivel medio del mar o un banco de nivel local.",
    },
    {
      id: "m1-16",
      name: "La escala relaciona la distancia del plano…",
      type: "image",
      durationInSeconds: 5.9,
      imageUrl: `${MEDIA}/fotografia_16.png`,
      audioUrl: `${MEDIA}/escena_16.mp3`,
      accentColor: "#1a6bff",
      script: "La escala relaciona la distancia del plano con la distancia real del terreno.",
    },
    {
      id: "m1-17",
      name: "Una escala uno a quinientos significa que…",
      type: "image",
      durationInSeconds: 6.7,
      imageUrl: `${MEDIA}/fotografia_17.png`,
      audioUrl: `${MEDIA}/escena_17.mp3`,
      accentColor: "#1a6bff",
      script: "Una escala uno a quinientos significa que un centimetro equivale a quinientos centimetros reales.",
    },
    {
      id: "m1-18",
      name: "El azimut es el ángulo horizontal medido en…",
      type: "image",
      durationInSeconds: 5.3,
      imageUrl: `${MEDIA}/fotografia_18.png`,
      audioUrl: `${MEDIA}/escena_18.mp3`,
      accentColor: "#1a6bff",
      script: "El azimut es el ángulo horizontal medido en sentido horario desde el norte.",
    },
    {
      id: "m1-19",
      name: "Va de cero a trescientos sesenta grados y…",
      type: "image",
      durationInSeconds: 5.5,
      imageUrl: `${MEDIA}/fotografia_19.png`,
      audioUrl: `${MEDIA}/escena_19.mp3`,
      accentColor: "#1a6bff",
      script: "Va de cero a trescientos sesenta grados y define la dirección de una linea.",
    },
    {
      id: "m1-20",
      name: "El rumbo expresa esa misma dirección por…",
      type: "image",
      durationInSeconds: 5.9,
      imageUrl: `${MEDIA}/fotografia_20.png`,
      audioUrl: `${MEDIA}/escena_20.mp3`,
      accentColor: "#1a6bff",
      script: "El rumbo expresa esa misma dirección por cuadrantes, desde el norte o el sur.",
    },
    {
      id: "m1-21",
      name: "Se mide de cero a noventa grados hacia el…",
      type: "image",
      durationInSeconds: 5.4,
      imageUrl: `${MEDIA}/fotografia_21.png`,
      audioUrl: `${MEDIA}/escena_21.mp3`,
      accentColor: "#1a6bff",
      script: "Se mide de cero a noventa grados hacia el este o hacia el oeste.",
    },
    {
      id: "m1-22",
      name: "El contrazimut es el azimut de la misma…",
      type: "image",
      durationInSeconds: 5.5,
      imageUrl: `${MEDIA}/fotografia_22.png`,
      audioUrl: `${MEDIA}/escena_22.mp3`,
      accentColor: "#1a6bff",
      script: "El contrazimut es el azimut de la misma linea en sentido contrario.",
    },
    {
      id: "m1-23",
      name: "Se obtiene sumando o restando ciento…",
      type: "image",
      durationInSeconds: 5.8,
      imageUrl: `${MEDIA}/fotografia_23.png`,
      audioUrl: `${MEDIA}/escena_23.mp3`,
      accentColor: "#1a6bff",
      script: "Se obtiene sumando o restando ciento ochenta grados al azimut original.",
    },
    {
      id: "m1-24",
      name: "La cartera de campo es el registro ordenado…",
      type: "image",
      durationInSeconds: 5,
      imageUrl: `${MEDIA}/fotografia_24.png`,
      audioUrl: `${MEDIA}/escena_24.mp3`,
      accentColor: "#1a6bff",
      script: "La cartera de campo es el registro ordenado de todas tus lecturas.",
    },
    {
      id: "m1-25",
      name: "Sin una cartera bien diligenciada, los…",
      type: "image",
      durationInSeconds: 4.5,
      imageUrl: `${MEDIA}/fotografia_25.png`,
      audioUrl: `${MEDIA}/escena_25.mp3`,
      accentColor: "#1a6bff",
      script: "Sin una cartera bien diligenciada, los datos del levantamiento no sirven.",
    },
    {
      id: "m1-26",
      name: "Las coordenadas geograficas ubican un punto…",
      type: "image",
      durationInSeconds: 5,
      imageUrl: `${MEDIA}/fotografia_26.png`,
      audioUrl: `${MEDIA}/escena_26.mp3`,
      accentColor: "#1a6bff",
      script: "Las coordenadas geograficas ubican un punto con latitud y longitud.",
    },
    {
      id: "m1-27",
      name: "Se usan como referencia global sobre la…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_27.png`,
      audioUrl: `${MEDIA}/escena_27.mp3`,
      accentColor: "#1a6bff",
      script: "Se usan como referencia global sobre la superficie terrestre.",
    },
    {
      id: "m1-28",
      name: "Las coordenadas UTM son una proyección…",
      type: "image",
      durationInSeconds: 4.8,
      imageUrl: `${MEDIA}/fotografia_28.png`,
      audioUrl: `${MEDIA}/escena_28.mp3`,
      accentColor: "#1a6bff",
      script: "Las coordenadas UTM son una proyección plana que trabaja en metros.",
    },
    {
      id: "m1-29",
      name: "Por eso son las más usadas en los…",
      type: "image",
      durationInSeconds: 3.5,
      imageUrl: `${MEDIA}/fotografia_29.png`,
      audioUrl: `${MEDIA}/escena_29.mp3`,
      accentColor: "#1a6bff",
      script: "Por eso son las más usadas en los levantamientos de obra.",
    },
    {
      id: "m1-30",
      name: "Los bancos de nivel, tambien llamados…",
      type: "image",
      durationInSeconds: 6.1,
      imageUrl: `${MEDIA}/fotografia_30.png`,
      audioUrl: `${MEDIA}/escena_30.mp3`,
      accentColor: "#1a6bff",
      script: "Los bancos de nivel, tambien llamados mojones, son puntos fijos con cota conocida.",
    },
    {
      id: "m1-31",
      name: "Desde ellos se transportan las elevaciones…",
      type: "image",
      durationInSeconds: 3.8,
      imageUrl: `${MEDIA}/fotografia_31.png`,
      audioUrl: `${MEDIA}/escena_31.mp3`,
      accentColor: "#1a6bff",
      script: "Desde ellos se transportan las elevaciones a toda la obra.",
    },
    {
      id: "m1-32",
      name: "Verifica siempre el sistema de coordenadas…",
      type: "image",
      durationInSeconds: 4.6,
      imageUrl: `${MEDIA}/fotografia_32.png`,
      audioUrl: `${MEDIA}/escena_32.mp3`,
      accentColor: "#1a6bff",
      script: "Verifica siempre el sistema de coordenadas y el datum del proyecto.",
    },
    {
      id: "m1-33",
      name: "En campo se trabaja en grados sexagesimales…",
      type: "image",
      durationInSeconds: 5,
      imageUrl: `${MEDIA}/fotografia_33.png`,
      audioUrl: `${MEDIA}/escena_33.mp3`,
      accentColor: "#1a6bff",
      script: "En campo se trabaja en grados sexagesimales y en metros.",
    },
    {
      id: "m1-34",
      name: "Confirma la unidad configurada en el…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_34.png`,
      audioUrl: `${MEDIA}/escena_34.mp3`,
      accentColor: "#1a6bff",
      script: "Confirma la unidad configurada en el instrumento antes de medir.",
    },
    {
      id: "m1-35",
      name: "Cada levantamiento tiene una tolerancia de…",
      type: "image",
      durationInSeconds: 4.3,
      imageUrl: `${MEDIA}/fotografia_35.png`,
      audioUrl: `${MEDIA}/escena_35.mp3`,
      accentColor: "#1a6bff",
      script: "Cada levantamiento tiene una tolerancia de error definida por norma.",
    },
    {
      id: "m1-36",
      name: "Si superas esa tolerancia, la medición debe…",
      type: "image",
      durationInSeconds: 4.6,
      imageUrl: `${MEDIA}/fotografia_36.png`,
      audioUrl: `${MEDIA}/escena_36.mp3`,
      accentColor: "#1a6bff",
      script: "Si superas esa tolerancia, la medición debe repetirse completa.",
    },
    {
      id: "m1-37",
      name: "Los errores más comunes nacen de un equipo…",
      type: "image",
      durationInSeconds: 3.9,
      imageUrl: `${MEDIA}/fotografia_37.png`,
      audioUrl: `${MEDIA}/escena_37.mp3`,
      accentColor: "#1a6bff",
      script: "Los errores más comunes nacen de un equipo mal nivelado.",
    },
    {
      id: "m1-38",
      name: "Tambien de lecturas incorrectas de mira,…",
      type: "image",
      durationInSeconds: 5.7,
      imageUrl: `${MEDIA}/fotografia_38.png`,
      audioUrl: `${MEDIA}/escena_38.mp3`,
      accentColor: "#1a6bff",
      script: "Tambien de lecturas incorrectas de mira, clima adverso y falta de calibración.",
    },
  ],
};
