import type { DynamicVideoProps } from "@video/schema/scene-schema";

// GENERADO por scripts/build-module-examples.ts — no editar a mano.
// Fuente: audio_m3/ + m3_fotografia/ + narraciones_m3_acentos_subtitulos.txt
// Una escena por línea de narración: su audio manda la duración y su
// fotografía es la imagen. La media vive en render-server/uploads/, así que el
// servidor de render tiene que estar arriba para verla.
const MEDIA = "http://localhost:4000/uploads/modulos/m3";

export const moduloTrabajoDeCampo: DynamicVideoProps = {
  settings: { subtitles: true },
  scenes: [
    {
      id: "m3-1",
      name: "Con los conceptos y los instrumentos…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_1.png`,
      audioUrl: `${MEDIA}/escena_1.mp3`,
      accentColor: "#f49e04",
      script: "Con los conceptos y los instrumentos claros, llega el trabajo de campo.",
    },
    {
      id: "m3-2",
      name: "Empecemos por la nivelación topográfica",
      type: "image",
      durationInSeconds: 3.3,
      imageUrl: `${MEDIA}/fotografia_2.png`,
      audioUrl: `${MEDIA}/escena_2.mp3`,
      accentColor: "#f49e04",
      script: "Empecemos por la nivelación topográfica.",
    },
    {
      id: "m3-3",
      name: "Nivelar es determinar la diferencia de…",
      type: "image",
      durationInSeconds: 5.3,
      imageUrl: `${MEDIA}/fotografia_3.png`,
      audioUrl: `${MEDIA}/escena_3.mp3`,
      accentColor: "#f49e04",
      script: "Nivelar es determinar la diferencia de altura entre dos o más puntos.",
    },
    {
      id: "m3-4",
      name: "La nivelación simple resuelve el desnivel…",
      type: "image",
      durationInSeconds: 5,
      imageUrl: `${MEDIA}/fotografia_4.png`,
      audioUrl: `${MEDIA}/escena_4.mp3`,
      accentColor: "#f49e04",
      script: "La nivelación simple resuelve el desnivel desde una sola estación.",
    },
    {
      id: "m3-5",
      name: "Sirve cuando los puntos están cerca y hay…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_5.png`,
      audioUrl: `${MEDIA}/escena_5.mp3`,
      accentColor: "#f49e04",
      script: "Sirve cuando los puntos están cerca y hay visibilidad directa.",
    },
    {
      id: "m3-6",
      name: "La nivelación compuesta encadena varias…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_6.png`,
      audioUrl: `${MEDIA}/escena_6.mp3`,
      accentColor: "#f49e04",
      script: "La nivelación compuesta encadena varias estaciones consecutivas.",
    },
    {
      id: "m3-7",
      name: "Así se transportan cotas a lo largo de…",
      type: "image",
      durationInSeconds: 4,
      imageUrl: `${MEDIA}/fotografia_7.png`,
      audioUrl: `${MEDIA}/escena_7.mp3`,
      accentColor: "#f49e04",
      script: "Así se transportan cotas a lo largo de distancias mayores.",
    },
    {
      id: "m3-8",
      name: "En cada estación se toma una lectura atrás…",
      type: "image",
      durationInSeconds: 4,
      imageUrl: `${MEDIA}/fotografia_8.png`,
      audioUrl: `${MEDIA}/escena_8.mp3`,
      accentColor: "#f49e04",
      script: "En cada estación se toma una lectura atrás y una adelante.",
    },
    {
      id: "m3-9",
      name: "Las lecturas intermedias sirven para…",
      type: "image",
      durationInSeconds: 4.2,
      imageUrl: `${MEDIA}/fotografia_9.png`,
      audioUrl: `${MEDIA}/escena_9.mp3`,
      accentColor: "#f49e04",
      script: "Las lecturas intermedias sirven para levantar puntos del terreno.",
    },
    {
      id: "m3-10",
      name: "Todo se anota en la libreta o cartera de…",
      type: "image",
      durationInSeconds: 3.4,
      imageUrl: `${MEDIA}/fotografia_10.png`,
      audioUrl: `${MEDIA}/escena_10.mp3`,
      accentColor: "#f49e04",
      script: "Todo se anota en la libreta o cartera de campo.",
    },
    {
      id: "m3-11",
      name: "Un registro ordenado permite calcular las…",
      type: "image",
      durationInSeconds: 4.8,
      imageUrl: `${MEDIA}/fotografia_11.png`,
      audioUrl: `${MEDIA}/escena_11.mp3`,
      accentColor: "#f49e04",
      script: "Un registro ordenado permite calcular las cotas después sin errores.",
    },
    {
      id: "m3-12",
      name: "Si la cartera está mal diligenciada, hay…",
      type: "image",
      durationInSeconds: 5.4,
      imageUrl: `${MEDIA}/fotografia_12.png`,
      audioUrl: `${MEDIA}/escena_12.mp3`,
      accentColor: "#f49e04",
      script: "Si la cartera está mal diligenciada, hay que volver a campo.",
    },
    {
      id: "m3-13",
      name: "El segundo metodo clave es la poligonal",
      type: "image",
      durationInSeconds: 3.3,
      imageUrl: `${MEDIA}/fotografia_13.png`,
      audioUrl: `${MEDIA}/escena_13.mp3`,
      accentColor: "#f49e04",
      script: "El segundo metodo clave es la poligonal.",
    },
    {
      id: "m3-14",
      name: "Una poligonal es una serie de líneas que…",
      type: "image",
      durationInSeconds: 4.7,
      imageUrl: `${MEDIA}/fotografia_14.png`,
      audioUrl: `${MEDIA}/escena_14.mp3`,
      accentColor: "#f49e04",
      script: "Una poligonal es una serie de líneas que conectan puntos de control.",
    },
    {
      id: "m3-15",
      name: "La poligonal cerrada parte de un punto y…",
      type: "image",
      durationInSeconds: 4.8,
      imageUrl: `${MEDIA}/fotografia_15.png`,
      audioUrl: `${MEDIA}/escena_15.mp3`,
      accentColor: "#f49e04",
      script: "La poligonal cerrada parte de un punto y regresa al mismo punto.",
    },
    {
      id: "m3-16",
      name: "Eso permite verificar el error de cierre…",
      type: "image",
      durationInSeconds: 4.2,
      imageUrl: `${MEDIA}/fotografia_16.png`,
      audioUrl: `${MEDIA}/escena_16.mp3`,
      accentColor: "#f49e04",
      script: "Eso permite verificar el error de cierre angular y lineal.",
    },
    {
      id: "m3-17",
      name: "Por eso es la base del control topográfico…",
      type: "image",
      durationInSeconds: 3.2,
      imageUrl: `${MEDIA}/fotografia_17.png`,
      audioUrl: `${MEDIA}/escena_17.mp3`,
      accentColor: "#f49e04",
      script: "Por eso es la base del control topográfico de la obra.",
    },
    {
      id: "m3-18",
      name: "La poligonal abierta conecta dos puntos de…",
      type: "image",
      durationInSeconds: 4.7,
      imageUrl: `${MEDIA}/fotografia_18.png`,
      audioUrl: `${MEDIA}/escena_18.mp3`,
      accentColor: "#f49e04",
      script: "La poligonal abierta conecta dos puntos de control distintos.",
    },
    {
      id: "m3-19",
      name: "No permite verificación directa del cierre,…",
      type: "image",
      durationInSeconds: 5,
      imageUrl: `${MEDIA}/fotografia_19.png`,
      audioUrl: `${MEDIA}/escena_19.mp3`,
      accentColor: "#f49e04",
      script: "No permite verificación directa del cierre, así que exige más cuidado.",
    },
    {
      id: "m3-20",
      name: "En ambos casos se compara el error obtenido…",
      type: "image",
      durationInSeconds: 4.3,
      imageUrl: `${MEDIA}/fotografia_20.png`,
      audioUrl: `${MEDIA}/escena_20.mp3`,
      accentColor: "#f49e04",
      script: "En ambos casos se compara el error obtenido contra la tolerancia.",
    },
    {
      id: "m3-21",
      name: "Si el error excede la tolerancia, la…",
      type: "image",
      durationInSeconds: 4.2,
      imageUrl: `${MEDIA}/fotografia_21.png`,
      audioUrl: `${MEDIA}/escena_21.mp3`,
      accentColor: "#f49e04",
      script: "Si el error excede la tolerancia, la poligonal se repite.",
    },
    {
      id: "m3-22",
      name: "El tercer bloque es el trazado y el…",
      type: "image",
      durationInSeconds: 3.5,
      imageUrl: `${MEDIA}/fotografia_22.png`,
      audioUrl: `${MEDIA}/escena_22.mp3`,
      accentColor: "#f49e04",
      script: "El tercer bloque es el trazado y el replanteo.",
    },
    {
      id: "m3-23",
      name: "Trazar es ubicar en el terreno los…",
      type: "image",
      durationInSeconds: 4.5,
      imageUrl: `${MEDIA}/fotografia_23.png`,
      audioUrl: `${MEDIA}/escena_23.mp3`,
      accentColor: "#f49e04",
      script: "Trazar es ubicar en el terreno los elementos del diseño.",
    },
    {
      id: "m3-24",
      name: "Ejes, limites y niveles se materializan…",
      type: "image",
      durationInSeconds: 5.5,
      imageUrl: `${MEDIA}/fotografia_24.png`,
      audioUrl: `${MEDIA}/escena_24.mp3`,
      accentColor: "#f49e04",
      script: "Ejes, limites y niveles se materializan desde las coordenadas del proyecto.",
    },
    {
      id: "m3-25",
      name: "Replantear es llevar al campo toda la…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_25.png`,
      audioUrl: `${MEDIA}/escena_25.mp3`,
      accentColor: "#f49e04",
      script: "Replantear es llevar al campo toda la información del proyecto.",
    },
    {
      id: "m3-26",
      name: "Por ejemplo, plasmar el eje de la futura vía",
      type: "image",
      durationInSeconds: 3.5,
      imageUrl: `${MEDIA}/fotografia_26.png`,
      audioUrl: `${MEDIA}/escena_26.mp3`,
      accentColor: "#f49e04",
      script: "Por ejemplo, plasmar el eje de la futura vía.",
    },
    {
      id: "m3-27",
      name: "Determinar la banca de la vía sobre el…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_27.png`,
      audioUrl: `${MEDIA}/escena_27.mp3`,
      accentColor: "#f49e04",
      script: "Determinar la banca de la vía sobre el terreno real.",
    },
    {
      id: "m3-28",
      name: "Y replantear obras civiles como pluviales y…",
      type: "image",
      durationInSeconds: 4.3,
      imageUrl: `${MEDIA}/fotografia_28.png`,
      audioUrl: `${MEDIA}/escena_28.mp3`,
      accentColor: "#f49e04",
      script: "Y replantear obras civiles como pluviales y alcantarillado.",
    },
    {
      id: "m3-29",
      name: "Después se verifica que lo construido…",
      type: "image",
      durationInSeconds: 4,
      imageUrl: `${MEDIA}/fotografia_29.png`,
      audioUrl: `${MEDIA}/escena_29.mp3`,
      accentColor: "#f49e04",
      script: "Después se verifica que lo construido coincida con lo diseñado.",
    },
    {
      id: "m3-30",
      name: "Siempre dentro de la tolerancia establecida…",
      type: "image",
      durationInSeconds: 4.6,
      imageUrl: `${MEDIA}/fotografia_30.png`,
      audioUrl: `${MEDIA}/escena_30.mp3`,
      accentColor: "#f49e04",
      script: "Siempre dentro de la tolerancia establecida en las especificaciones.",
    },
    {
      id: "m3-31",
      name: "Los puntos clave se señalizan con estacas,…",
      type: "image",
      durationInSeconds: 4.7,
      imageUrl: `${MEDIA}/fotografia_31.png`,
      audioUrl: `${MEDIA}/escena_31.mp3`,
      accentColor: "#f49e04",
      script: "Los puntos clave se señalizan con estacas, pintura y mojones.",
    },
    {
      id: "m3-32",
      name: "Sobre los mojones se hace el traslado de…",
      type: "image",
      durationInSeconds: 5.2,
      imageUrl: `${MEDIA}/fotografia_32.png`,
      audioUrl: `${MEDIA}/escena_32.mp3`,
      accentColor: "#f49e04",
      script: "Sobre los mojones se hace el traslado de coordenadas de un punto armado.",
    },
    {
      id: "m3-33",
      name: "Una marca protegida evita repetir dias…",
      type: "image",
      durationInSeconds: 4.3,
      imageUrl: `${MEDIA}/fotografia_33.png`,
      audioUrl: `${MEDIA}/escena_33.mp3`,
      accentColor: "#f49e04",
      script: "Una marca protegida evita repetir dias enteros de trabajo.",
    },
    {
      id: "m3-34",
      name: "Nada de esto vale si se trabaja sin…",
      type: "image",
      durationInSeconds: 3.2,
      imageUrl: `${MEDIA}/fotografia_34.png`,
      audioUrl: `${MEDIA}/escena_34.mp3`,
      accentColor: "#f49e04",
      script: "Nada de esto vale si se trabaja sin seguridad.",
    },
    {
      id: "m3-35",
      name: "El uso del equipo de protección personal es…",
      type: "image",
      durationInSeconds: 3.8,
      imageUrl: `${MEDIA}/fotografia_35.png`,
      audioUrl: `${MEDIA}/escena_35.mp3`,
      accentColor: "#f49e04",
      script: "El uso del equipo de protección personal es obligatorio.",
    },
    {
      id: "m3-36",
      name: "Señaliza el area de trabajo antes de…",
      type: "image",
      durationInSeconds: 3.9,
      imageUrl: `${MEDIA}/fotografia_36.png`,
      audioUrl: `${MEDIA}/escena_36.mp3`,
      accentColor: "#f49e04",
      script: "Señaliza el area de trabajo antes de iniciar la medición.",
    },
    {
      id: "m3-37",
      name: "Extrema el cuidado en cruces con maquinaria…",
      type: "image",
      durationInSeconds: 4.6,
      imageUrl: `${MEDIA}/fotografia_37.png`,
      audioUrl: `${MEDIA}/escena_37.mp3`,
      accentColor: "#f49e04",
      script: "Extrema el cuidado en cruces con maquinaria y vías activas.",
    },
    {
      id: "m3-38",
      name: "Y mantén comunicación constante con todo el…",
      type: "image",
      durationInSeconds: 3.9,
      imageUrl: `${MEDIA}/fotografia_38.png`,
      audioUrl: `${MEDIA}/escena_38.mp3`,
      accentColor: "#f49e04",
      script: "Y mantén comunicación constante con todo el equipo de campo.",
    },
  ],
};
