import type { DynamicVideoProps } from "@video/schema/scene-schema";

// GENERADO por scripts/build-module-examples.ts — no editar a mano.
// Fuente: audio_m2/ + m2_fotografia/ + narraciones_m2_acentos_subtitulos.txt
// Una escena por línea de narración: su audio manda la duración y su
// fotografía es la imagen. La media vive en render-server/uploads/, así que el
// servidor de render tiene que estar arriba para verla.
const MEDIA = "http://localhost:4000/uploads/modulos/m2";

export const moduloInstrumentos: DynamicVideoProps = {
  settings: { subtitles: true },
  scenes: [
    {
      id: "m2-1",
      name: "Los instrumentos son la extensión de las…",
      type: "image",
      durationInSeconds: 5.3,
      imageUrl: `${MEDIA}/fotografia_1.png`,
      audioUrl: `${MEDIA}/escena_1.mp3`,
      accentColor: "#0e9f6e",
      script: "Los instrumentos son la extensión de las manos del topografo en campo.",
    },
    {
      id: "m2-2",
      name: "Empecemos por los tradicionales, que siguen…",
      type: "image",
      durationInSeconds: 4.9,
      imageUrl: `${MEDIA}/fotografia_2.png`,
      audioUrl: `${MEDIA}/escena_2.mp3`,
      accentColor: "#0e9f6e",
      script: "Empecemos por los tradicionales, que siguen siendo indispensables.",
    },
    {
      id: "m2-3",
      name: "La cinta métrica o wincha mide distancias…",
      type: "image",
      durationInSeconds: 5.3,
      imageUrl: `${MEDIA}/fotografia_3.png`,
      audioUrl: `${MEDIA}/escena_3.mp3`,
      accentColor: "#0e9f6e",
      script: "La cinta métrica o wincha mide distancias cortas de forma directa.",
    },
    {
      id: "m2-4",
      name: "Requiere tension constante para que la…",
      type: "image",
      durationInSeconds: 4.2,
      imageUrl: `${MEDIA}/fotografia_4.png`,
      audioUrl: `${MEDIA}/escena_4.mp3`,
      accentColor: "#0e9f6e",
      script: "Requiere tension constante para que la lectura sea confiable.",
    },
    {
      id: "m2-5",
      name: "En mediciones de precisión se corrige por…",
      type: "image",
      durationInSeconds: 3.7,
      imageUrl: `${MEDIA}/fotografia_5.png`,
      audioUrl: `${MEDIA}/escena_5.mp3`,
      accentColor: "#0e9f6e",
      script: "En mediciones de precisión se corrige por temperatura.",
    },
    {
      id: "m2-6",
      name: "Los jalones materializan y hacen visible un…",
      type: "image",
      durationInSeconds: 4.8,
      imageUrl: `${MEDIA}/fotografia_6.png`,
      audioUrl: `${MEDIA}/escena_6.mp3`,
      accentColor: "#0e9f6e",
      script: "Los jalones materializan y hacen visible un punto en el terreno.",
    },
    {
      id: "m2-7",
      name: "La plomada verifica que ese punto este…",
      type: "image",
      durationInSeconds: 4.8,
      imageUrl: `${MEDIA}/fotografia_7.png`,
      audioUrl: `${MEDIA}/escena_7.mp3`,
      accentColor: "#0e9f6e",
      script: "La plomada verifica que ese punto este perfectamente vertical.",
    },
    {
      id: "m2-8",
      name: "El nivel de mano permite chequeos rapidos…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_8.png`,
      audioUrl: `${MEDIA}/escena_8.mp3`,
      accentColor: "#0e9f6e",
      script: "El nivel de mano permite chequeos rapidos de horizontalidad y desnivel.",
    },
    {
      id: "m2-9",
      name: "Es útil para verificaciones, no para…",
      type: "image",
      durationInSeconds: 4.3,
      imageUrl: `${MEDIA}/fotografia_9.png`,
      audioUrl: `${MEDIA}/escena_9.mp3`,
      accentColor: "#0e9f6e",
      script: "Es útil para verificaciones, no para mediciones definitivas.",
    },
    {
      id: "m2-10",
      name: "La mira o estadal es una regla graduada que…",
      type: "image",
      durationInSeconds: 5.3,
      imageUrl: `${MEDIA}/fotografia_10.png`,
      audioUrl: `${MEDIA}/escena_10.mp3`,
      accentColor: "#0e9f6e",
      script: "La mira o estadal es una regla graduada que se lee a distancia.",
    },
    {
      id: "m2-11",
      name: "Se observa a traves del nivel óptico o de…",
      type: "image",
      durationInSeconds: 4.2,
      imageUrl: `${MEDIA}/fotografia_11.png`,
      audioUrl: `${MEDIA}/escena_11.mp3`,
      accentColor: "#0e9f6e",
      script: "Se observa a traves del nivel óptico o de la estación total.",
    },
    {
      id: "m2-12",
      name: "Con ella se determinan las diferencias de…",
      type: "image",
      durationInSeconds: 3.9,
      imageUrl: `${MEDIA}/fotografia_12.png`,
      audioUrl: `${MEDIA}/escena_12.mp3`,
      accentColor: "#0e9f6e",
      script: "Con ella se determinan las diferencias de altura entre puntos.",
    },
    {
      id: "m2-13",
      name: "Pasemos ahora a los instrumentos ópticos y…",
      type: "image",
      durationInSeconds: 5,
      imageUrl: `${MEDIA}/fotografia_13.png`,
      audioUrl: `${MEDIA}/escena_13.mp3`,
      accentColor: "#0e9f6e",
      script: "Pasemos ahora a los instrumentos ópticos y electrónicos.",
    },
    {
      id: "m2-14",
      name: "El nivel óptico define una linea de visual…",
      type: "image",
      durationInSeconds: 4.7,
      imageUrl: `${MEDIA}/fotografia_14.png`,
      audioUrl: `${MEDIA}/escena_14.mp3`,
      accentColor: "#0e9f6e",
      script: "El nivel óptico define una linea de visual perfectamente horizontal.",
    },
    {
      id: "m2-15",
      name: "Se usa sobre todo para nivelación y…",
      type: "image",
      durationInSeconds: 4.1,
      imageUrl: `${MEDIA}/fotografia_15.png`,
      audioUrl: `${MEDIA}/escena_15.mp3`,
      accentColor: "#0e9f6e",
      script: "Se usa sobre todo para nivelación y transporte de cotas.",
    },
    {
      id: "m2-16",
      name: "La estación total integra varias funciones…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_16.png`,
      audioUrl: `${MEDIA}/escena_16.mp3`,
      accentColor: "#0e9f6e",
      script: "La estación total integra varias funciones en un solo equipo.",
    },
    {
      id: "m2-17",
      name: "Su anteojo telescópico permite visar el…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_17.png`,
      audioUrl: `${MEDIA}/escena_17.mp3`,
      accentColor: "#0e9f6e",
      script: "Su anteojo telescópico permite visar el punto con precisión.",
    },
    {
      id: "m2-18",
      name: "La base nivelante sostiene y nivela el…",
      type: "image",
      durationInSeconds: 5.3,
      imageUrl: `${MEDIA}/fotografia_18.png`,
      audioUrl: `${MEDIA}/escena_18.mp3`,
      accentColor: "#0e9f6e",
      script: "La base nivelante sostiene y nivela el instrumento sobre el tripode.",
    },
    {
      id: "m2-19",
      name: "La plomada láser u óptica lo centra…",
      type: "image",
      durationInSeconds: 4.7,
      imageUrl: `${MEDIA}/fotografia_19.png`,
      audioUrl: `${MEDIA}/escena_19.mp3`,
      accentColor: "#0e9f6e",
      script: "La plomada láser u óptica lo centra exactamente sobre el punto.",
    },
    {
      id: "m2-20",
      name: "La pantalla y el teclado controlan la…",
      type: "image",
      durationInSeconds: 4.9,
      imageUrl: `${MEDIA}/fotografia_20.png`,
      audioUrl: `${MEDIA}/escena_20.mp3`,
      accentColor: "#0e9f6e",
      script: "La pantalla y el teclado controlan la medición y almacenan los datos.",
    },
    {
      id: "m2-21",
      name: "El distanciómetro electrónico mide la…",
      type: "image",
      durationInSeconds: 4.7,
      imageUrl: `${MEDIA}/fotografia_21.png`,
      audioUrl: `${MEDIA}/escena_21.mp3`,
      accentColor: "#0e9f6e",
      script: "El distanciómetro electrónico mide la distancia sin contacto físico.",
    },
    {
      id: "m2-22",
      name: "La estación total mide ángulos…",
      type: "image",
      durationInSeconds: 5.6,
      imageUrl: `${MEDIA}/fotografia_22.png`,
      audioUrl: `${MEDIA}/escena_22.mp3`,
      accentColor: "#0e9f6e",
      script: "La estación total mide ángulos horizontales, verticales y distancias.",
    },
    {
      id: "m2-23",
      name: "Y lo hace de forma simultánea en una sola…",
      type: "image",
      durationInSeconds: 3.6,
      imageUrl: `${MEDIA}/fotografia_23.png`,
      audioUrl: `${MEDIA}/escena_23.mp3`,
      accentColor: "#0e9f6e",
      script: "Y lo hace de forma simultánea en una sola visada.",
    },
    {
      id: "m2-24",
      name: "Con esos datos calcula las coordenadas de…",
      type: "image",
      durationInSeconds: 4.2,
      imageUrl: `${MEDIA}/fotografia_24.png`,
      audioUrl: `${MEDIA}/escena_24.mp3`,
      accentColor: "#0e9f6e",
      script: "Con esos datos calcula las coordenadas de cualquier punto visado.",
    },
    {
      id: "m2-25",
      name: "El tercer grupo de equipos es el…",
      type: "image",
      durationInSeconds: 4.1,
      imageUrl: `${MEDIA}/fotografia_25.png`,
      audioUrl: `${MEDIA}/escena_25.mp3`,
      accentColor: "#0e9f6e",
      script: "El tercer grupo de equipos es el posicionamiento satelital.",
    },
    {
      id: "m2-26",
      name: "GNSS agrupa sistemas como GPS, GLONASS y…",
      type: "image",
      durationInSeconds: 5.1,
      imageUrl: `${MEDIA}/fotografia_26.png`,
      audioUrl: `${MEDIA}/escena_26.mp3`,
      accentColor: "#0e9f6e",
      script: "GNSS agrupa sistemas como GPS, GLONASS y Galileo.",
    },
    {
      id: "m2-27",
      name: "Permite obtener coordenadas directamente en…",
      type: "image",
      durationInSeconds: 4.6,
      imageUrl: `${MEDIA}/fotografia_27.png`,
      audioUrl: `${MEDIA}/escena_27.mp3`,
      accentColor: "#0e9f6e",
      script: "Permite obtener coordenadas directamente en campo desde los satélites.",
    },
    {
      id: "m2-28",
      name: "El GNSS de precisión trabaja con correccion…",
      type: "image",
      durationInSeconds: 5.2,
      imageUrl: `${MEDIA}/fotografia_28.png`,
      audioUrl: `${MEDIA}/escena_28.mp3`,
      accentColor: "#0e9f6e",
      script: "El GNSS de precisión trabaja con correccion diferencial en tiempo real.",
    },
    {
      id: "m2-29",
      name: "Ese modo se conoce como RTK y alcanza…",
      type: "image",
      durationInSeconds: 5.5,
      imageUrl: `${MEDIA}/fotografia_29.png`,
      audioUrl: `${MEDIA}/escena_29.mp3`,
      accentColor: "#0e9f6e",
      script: "Ese modo se conoce como RTK y alcanza precisiones centimétricas.",
    },
    {
      id: "m2-30",
      name: "Es ideal para levantar grandes extensiones…",
      type: "image",
      durationInSeconds: 4,
      imageUrl: `${MEDIA}/fotografia_30.png`,
      audioUrl: `${MEDIA}/escena_30.mp3`,
      accentColor: "#0e9f6e",
      script: "Es ideal para levantar grandes extensiones en poco tiempo.",
    },
    {
      id: "m2-31",
      name: "Su mayor ventaja es que no requiere…",
      type: "image",
      durationInSeconds: 4.8,
      imageUrl: `${MEDIA}/fotografia_31.png`,
      audioUrl: `${MEDIA}/escena_31.mp3`,
      accentColor: "#0e9f6e",
      script: "Su mayor ventaja es que no requiere intervisibilidad entre puntos.",
    },
    {
      id: "m2-32",
      name: "Pero pierde señal bajo cobertura vegetal…",
      type: "image",
      durationInSeconds: 3.4,
      imageUrl: `${MEDIA}/fotografia_32.png`,
      audioUrl: `${MEDIA}/escena_32.mp3`,
      accentColor: "#0e9f6e",
      script: "Pero pierde señal bajo cobertura vegetal densa.",
    },
    {
      id: "m2-33",
      name: "Tambien falla cerca de estructuras y en…",
      type: "image",
      durationInSeconds: 5.3,
      imageUrl: `${MEDIA}/fotografia_33.png`,
      audioUrl: `${MEDIA}/escena_33.mp3`,
      accentColor: "#0e9f6e",
      script: "Tambien falla cerca de estructuras y en zonas urbanas con edificios altos.",
    },
    {
      id: "m2-34",
      name: "Ningún instrumento reemplaza al otro: se…",
      type: "image",
      durationInSeconds: 5.7,
      imageUrl: `${MEDIA}/fotografia_34.png`,
      audioUrl: `${MEDIA}/escena_34.mp3`,
      accentColor: "#0e9f6e",
      script: "Ningún instrumento reemplaza al otro: se complementan según el trabajo.",
    },
    {
      id: "m2-35",
      name: "Todos exigen lo mismo: buen armado,…",
      type: "image",
      durationInSeconds: 6.3,
      imageUrl: `${MEDIA}/fotografia_35.png`,
      audioUrl: `${MEDIA}/escena_35.mp3`,
      accentColor: "#0e9f6e",
      script: "Todos exigen lo mismo: buen armado, nivelación correcta y calibración vigente.",
    },
    {
      id: "m2-36",
      name: "Un equipo mal armado convierte en error…",
      type: "image",
      durationInSeconds: 4.4,
      imageUrl: `${MEDIA}/fotografia_36.png`,
      audioUrl: `${MEDIA}/escena_36.mp3`,
      accentColor: "#0e9f6e",
      script: "Un equipo mal armado convierte en error todo lo que mide después.",
    },
  ],
};
