import type { DynamicVideoProps } from "@video/schema/scene-schema";

// One of the sample scripts the editor can open — product content, not part of
// the contract: the engine in src/video/ never imports it.
export const onboardingComercial: DynamicVideoProps = {
  settings: { subtitles: false },
  scenes: [
    {
      id: "s1",
      script:
        "Bienvenido al equipo comercial. En los próximos treinta días vas a pasar de conocer la empresa a cerrar tus primeras oportunidades con autonomía.",
      name: "Bienvenido al equipo comercial",
      type: "canvas",
      layout: "portada",
      durationInSeconds: 8,
      accentColor: "#1a6bff",
      background: "gradient",
      audioUrl: "https://remotion.media/illuminati-confirmed.wav",
      audioVolume: 1,
      layers: [
        {
          id: "s1-eyebrow",
          type: "text",
          variant: "eyebrow",
          text: "Tus primeros treinta días",
          x: 6,
          y: 32,
          w: 40,
          h: 6,
        },
        {
          id: "s1-title",
          type: "text",
          variant: "title",
          text: "Onboarding comercial",
          x: 6,
          y: 40,
          w: 40,
          h: 18,
        },
        {
          id: "s1-body",
          type: "text",
          variant: "body",
          text: "De conocer la empresa a cerrar tus primeras oportunidades con autonomía.",
          x: 6,
          y: 60,
          w: 38,
          h: 14,
        },
        {
          id: "s1-plate",
          type: "shape",
          fill: "white",
          x: 50,
          y: 12,
          w: 42,
          h: 72,
          rotation: -11,
        },
        {
          id: "s1-photo",
          type: "image",
          src: "https://picsum.photos/seed/ubits-team/1200/1200",
          x: 52,
          y: 12,
          w: 40,
          h: 76,
        },
        {
          id: "s1-badge",
          type: "badge",
          title: "Treinta días",
          subtitle: "Cuatro semanas, cuatro objetivos",
          x: 60,
          y: 70,
          w: 32,
          h: 14,
        },
      ],
    },
    {
      id: "s2",
      script:
        "Este onboarding tiene cuatro semanas, y cada una tiene un objetivo claro.",
      name: "Este onboarding tiene cuatro semanas",
      type: "canvas",
      layout: "agenda-indice",
      durationInSeconds: 9,
      accentColor: "#2ec6ff",
      background: "dark",
      layers: [
        {
          id: "s2-title",
          type: "text",
          variant: "title",
          text: "Cuatro semanas, cuatro objetivos",
          x: 8,
          y: 16,
          w: 80,
          h: 12,
        },
        {
          id: "s2-items",
          type: "list",
          ordered: true,
          items: [
            "Semana 1 — Contexto y producto",
            "Semana 2 — Discurso comercial",
            "Semana 3 — Práctica con casos reales",
            "Semana 4 — Primeras oportunidades",
          ],
          x: 8,
          y: 32,
          w: 80,
          h: 52,
        },
      ],
    },
    {
      id: "s3",
      script: "La semana uno es de contexto: entender qué vendemos y a quién.",
      name: "La semana uno es de contexto",
      type: "canvas",
      layout: "divisor-seccion",
      durationInSeconds: 7,
      accentColor: "#1a6bff",
      background: "accent",
      layers: [
        {
          id: "s3-title",
          type: "text",
          variant: "statement",
          text: "Semana 1: Contexto",
          x: 12,
          y: 42,
          w: 76,
          h: 16,
        },
      ],
    },
    {
      id: "s4",
      script:
        "Empieza por el producto. Conócelo a fondo antes de hablar con un cliente.",
      name: "Empieza por el producto",
      type: "canvas",
      layout: "texto-imagen",
      durationInSeconds: 8,
      accentColor: "#1a6bff",
      background: "light",
      layers: [
        {
          id: "s4-title",
          type: "text",
          variant: "title",
          text: "Empieza por el producto",
          x: 6,
          y: 34,
          w: 40,
          h: 16,
        },
        {
          id: "s4-body",
          type: "text",
          variant: "body",
          text: "Conoce a fondo lo que vendemos antes de hablar con un cliente.",
          x: 6,
          y: 52,
          w: 38,
          h: 16,
        },
        {
          id: "s4-photo",
          type: "image",
          src: "https://picsum.photos/seed/ubits-product/1200/1200",
          x: 52,
          y: 14,
          w: 42,
          h: 72,
        },
      ],
    },
    {
      id: "s5",
      script:
        "Revisa los casos de éxito para ver cómo se ve una venta bien hecha.",
      name: "Revisa los casos de éxito",
      type: "avatar",
      durationInSeconds: 5,
      videoUrl: "https://remotion.media/first-frame-at-4sec.webm",
    },
    {
      id: "s6",
      script:
        "Conoce el mercado: hoy tenemos más de ciento veinte clientes activos en tu territorio.",
      name: "Conoce el mercado",
      type: "canvas",
      layout: "dato-clave",
      durationInSeconds: 9,
      accentColor: "#1a6bff",
      background: "light",
      layers: [
        {
          id: "s6-stat",
          type: "stat",
          value: "+120",
          label: "Clientes activos en tu mercado",
          x: 22,
          y: 32,
          w: 56,
          h: 36,
        },
      ],
    },
    {
      id: "s7",
      script: "Configura tus herramientas antes de arrancar la semana dos.",
      name: "Configura tus herramientas",
      type: "canvas",
      layout: "lista-ordenada",
      durationInSeconds: 10,
      accentColor: "#3865f5",
      background: "light",
      layers: [
        {
          id: "s7-title",
          type: "text",
          variant: "title",
          text: "Configura tus herramientas",
          x: 8,
          y: 16,
          w: 70,
          h: 12,
        },
        {
          id: "s7-items",
          type: "list",
          ordered: true,
          items: [
            "Correo y calendario",
            "CRM comercial",
            "Canal de equipo en Slack",
            "Acceso al dashboard de ventas",
          ],
          x: 8,
          y: 32,
          w: 70,
          h: 48,
        },
      ],
    },
    {
      id: "s8",
      script: "Aprende la disciplina del CRM desde el primer día.",
      name: "Aprende la disciplina del CRM",
      type: "canvas",
      layout: "cita",
      durationInSeconds: 8,
      accentColor: "#2ec6ff",
      background: "dark",
      layers: [
        {
          id: "s8-quote",
          type: "quote",
          quote: "Lo que no está en el CRM, no existe.",
          author: "Equipo comercial UBITS",
          x: 14,
          y: 30,
          w: 72,
          h: 40,
        },
      ],
    },
    {
      id: "s9",
      script:
        "Cierra la semana uno con una prueba corta para validar lo aprendido.",
      name: "Cierra la semana uno con una prueba",
      type: "video",
      durationInSeconds: 5,
      videoUrl: "https://remotion.media/first-frame-at-4sec.webm",
    },
    {
      id: "s10",
      script:
        "La semana dos es de discurso: ahora que conoces el producto, toca contar la historia.",
      name: "La semana dos es de discurso",
      type: "canvas",
      layout: "afirmacion",
      durationInSeconds: 8,
      accentColor: "#f49e04",
      background: "dark",
      layers: [
        {
          id: "s10-statement",
          type: "text",
          variant: "statement",
          text: "Ahora que conoces el producto, es momento de contar la historia.",
          x: 12,
          y: 36,
          w: 76,
          h: 28,
        },
      ],
    },
  ],
};
