import type { DynamicVideoProps } from "@video/schema/scene-schema";

// Second sample script. Deliberately exercises what the first one does not:
// subtitles on, an image scene, and the una-columna / dos-columnas layouts.
export const seguridadInformacion: DynamicVideoProps = {
  settings: {
    subtitles: true,
    defaultTransition: { type: "zoom", durationInSeconds: 0.5 },
    subtitleStyle: {
      color: "#ffffff",
      outlineColor: "#0b0718",
      outlineWidth: 2,
      background: true,
      backgroundOpacity: 0.8,
    },
  },
  scenes: [
    {
      id: "sec1",
      script:
        "La seguridad de la información no es cosa del área de tecnología: empieza en tu escritorio, todos los días.",
      name: "Seguridad de la información",
      type: "canvas",
      layout: "portada",
      durationInSeconds: 8,
      accentColor: "#7c3aed",
      background: "gradient",
      layers: [
        {
          id: "sec1-eyebrow",
          type: "text",
          variant: "eyebrow",
          text: "Capacitación obligatoria",
          x: 6,
          y: 32,
          w: 40,
          h: 6,
        },
        {
          id: "sec1-title",
          type: "text",
          variant: "title",
          text: "Seguridad de la información",
          x: 6,
          y: 40,
          w: 40,
          h: 18,
        },
        {
          id: "sec1-body",
          type: "text",
          variant: "body",
          text: "No es cosa del área de tecnología: empieza en tu escritorio.",
          x: 6,
          y: 60,
          w: 38,
          h: 14,
        },
        {
          id: "sec1-plate",
          type: "shape",
          fill: "white",
          x: 50,
          y: 12,
          w: 42,
          h: 72,
          rotation: 9,
        },
        {
          id: "sec1-photo",
          type: "image",
          src: "https://picsum.photos/seed/ubits-security/1200/1200",
          x: 52,
          y: 12,
          w: 40,
          h: 76,
        },
        {
          id: "sec1-badge",
          type: "badge",
          title: "15 minutos",
          subtitle: "Cinco hábitos que evitan un incidente",
          x: 60,
          y: 70,
          w: 32,
          h: 14,
        },
      ],
    },
    {
      id: "sec2",
      script:
        "Vamos a repasar cuatro frentes, uno por cada riesgo que más nos golpea.",
      name: "Los cuatro frentes",
      type: "canvas",
      layout: "agenda-indice",
      durationInSeconds: 9,
      accentColor: "#a78bfa",
      background: "dark",
      layers: [
        {
          id: "sec2-title",
          type: "text",
          variant: "title",
          text: "Cuatro frentes",
          x: 8,
          y: 16,
          w: 80,
          h: 12,
        },
        {
          id: "sec2-items",
          type: "list",
          ordered: true,
          items: [
            "Contraseñas y acceso",
            "Phishing y correos sospechosos",
            "Información de clientes",
            "Qué hacer ante un incidente",
          ],
          x: 8,
          y: 32,
          w: 80,
          h: 52,
        },
      ],
    },
    {
      id: "sec3",
      script: "Primer frente: contraseñas y acceso.",
      name: "Frente 1: Contraseñas",
      type: "canvas",
      layout: "divisor-seccion",
      durationInSeconds: 6,
      accentColor: "#7c3aed",
      background: "accent",
      layers: [
        {
          id: "sec3-title",
          type: "text",
          variant: "title",
          text: "Frente 1: Contraseñas",
          x: 12,
          y: 42,
          w: 76,
          h: 16,
        },
      ],
    },
    {
      id: "sec4",
      script:
        "La mayoría de las brechas no empieza con un ataque sofisticado, sino con una contraseña reutilizada.",
      name: "Una contraseña reutilizada",
      type: "canvas",
      layout: "una-columna",
      durationInSeconds: 9,
      accentColor: "#7c3aed",
      background: "light",
      layers: [
        {
          id: "sec4-eyebrow",
          type: "text",
          variant: "eyebrow",
          text: "Cómo empieza una brecha",
          x: 8,
          y: 26,
          w: 40,
          h: 6,
        },
        {
          id: "sec4-title",
          type: "text",
          variant: "title",
          text: "Casi nunca es un ataque sofisticado",
          x: 8,
          y: 34,
          w: 70,
          h: 14,
        },
        {
          id: "sec4-body",
          type: "text",
          variant: "body",
          text: "Es una contraseña reutilizada en un servicio que ya fue filtrado. Basta una para abrir la puerta.",
          x: 8,
          y: 50,
          w: 70,
          h: 22,
        },
      ],
    },
    {
      id: "sec5",
      script:
        "Ocho de cada diez incidentes de acceso involucran credenciales débiles o robadas.",
      name: "8 de cada 10 incidentes",
      type: "canvas",
      layout: "dato-clave",
      durationInSeconds: 8,
      accentColor: "#7c3aed",
      background: "light",
      layers: [
        {
          id: "sec5-stat",
          type: "stat",
          value: "81%",
          label: "De los incidentes de acceso empiezan en una credencial débil",
          x: 22,
          y: 32,
          w: 56,
          h: 36,
        },
      ],
    },
    {
      id: "sec6",
      script:
        "La diferencia entre una contraseña débil y una fuerte se nota en segundos contra años.",
      name: "Débil frente a fuerte",
      type: "canvas",
      layout: "dos-columnas",
      durationInSeconds: 10,
      accentColor: "#7c3aed",
      background: "light",
      layers: [
        {
          id: "sec6-title",
          type: "text",
          variant: "title",
          text: "Débil frente a fuerte",
          x: 8,
          y: 14,
          w: 84,
          h: 12,
        },
        {
          id: "sec6-left",
          type: "text",
          variant: "body",
          text: "Débil: tu nombre y un año, repetida en cinco servicios. Se rompe en segundos.",
          x: 8,
          y: 34,
          w: 38,
          h: 40,
        },
        {
          id: "sec6-right",
          type: "text",
          variant: "body",
          text: "Fuerte: cuatro palabras sin relación, única por servicio y guardada en el gestor.",
          x: 54,
          y: 34,
          w: 38,
          h: 40,
        },
      ],
    },
    {
      id: "sec7",
      script:
        "Segundo frente: el phishing. Casi siempre llega por correo y siempre te apura.",
      name: "Frente 2: Phishing",
      type: "canvas",
      layout: "texto-imagen",
      durationInSeconds: 9,
      accentColor: "#7c3aed",
      background: "light",
      layers: [
        {
          id: "sec7-title",
          type: "text",
          variant: "title",
          text: "El phishing siempre te apura",
          x: 6,
          y: 34,
          w: 40,
          h: 16,
        },
        {
          id: "sec7-body",
          type: "text",
          variant: "body",
          text: "Urgencia, un remitente parecido al real y un enlace que pide credenciales.",
          x: 6,
          y: 52,
          w: 38,
          h: 16,
        },
        {
          id: "sec7-photo",
          type: "image",
          src: "https://picsum.photos/seed/ubits-phishing/1200/1200",
          x: 52,
          y: 14,
          w: 42,
          h: 72,
        },
      ],
    },
    {
      id: "sec8",
      script: "Así se ve un correo sospechoso cuando lo miras con calma.",
      name: "Un correo sospechoso",
      type: "image",
      durationInSeconds: 6,
      imageUrl: "https://picsum.photos/seed/ubits-inbox/1920/1080",
      accentColor: "#7c3aed",
    },
    {
      id: "sec9",
      script:
        "Tercer frente: la información de clientes. Si dudas de dónde va un dato, no lo muevas.",
      name: "Frente 3: Datos de clientes",
      type: "canvas",
      layout: "cita",
      durationInSeconds: 8,
      accentColor: "#a78bfa",
      background: "dark",
      layers: [
        {
          id: "sec9-quote",
          type: "quote",
          quote: "Si dudas de dónde va un dato, no lo muevas.",
          author: "Equipo de Seguridad UBITS",
          x: 14,
          y: 30,
          w: 72,
          h: 40,
        },
      ],
    },
    {
      id: "sec10",
      script:
        "Cuarto frente: qué hacer si sospechas. Cuatro pasos, en este orden.",
      name: "Qué hacer si sospechas",
      type: "canvas",
      layout: "lista-ordenada",
      durationInSeconds: 10,
      accentColor: "#7c3aed",
      background: "light",
      layers: [
        {
          id: "sec10-title",
          type: "text",
          variant: "title",
          text: "Qué hacer si sospechas",
          x: 8,
          y: 16,
          w: 70,
          h: 12,
        },
        {
          id: "sec10-items",
          type: "list",
          ordered: true,
          items: [
            "No hagas clic ni respondas",
            "Repórtalo al canal de seguridad",
            "Cambia la contraseña si ya la escribiste",
            "Avisa a tu líder",
          ],
          x: 8,
          y: 32,
          w: 70,
          h: 48,
        },
      ],
    },
    {
      id: "sec11",
      script: "Un minuto de duda ahorra semanas de contención.",
      name: "Un minuto de duda",
      type: "video",
      durationInSeconds: 5,
      videoUrl: "https://remotion.media/first-frame-at-4sec.webm",
    },
    {
      id: "sec12",
      script:
        "Reportar a tiempo nunca es exagerar: es la parte más barata de cualquier incidente.",
      name: "Reportar nunca es exagerar",
      type: "canvas",
      layout: "afirmacion",
      durationInSeconds: 8,
      accentColor: "#a78bfa",
      background: "dark",
      layers: [
        {
          id: "sec12-statement",
          type: "text",
          variant: "statement",
          text: "Reportar a tiempo nunca es exagerar.",
          x: 12,
          y: 36,
          w: 76,
          h: 28,
        },
      ],
    },
  ],
};
